using Microsoft.AspNet.OData.Extensions;
using Microsoft.AspNet.OData.Query;

namespace AutoMapper.AspNet.OData
{
    public static class ODataQueryOptionsExtensions
    {
        /// <summary>Adds the expand options to the result.</summary>
        /// <typeparam name="TModel">The type of the model.</typeparam>
        /// <param name="options">The odata options.</param>
        /// <autogeneratedoc />
        public static void AddExpandOptionsResult<TModel>(this ODataQueryOptions<TModel> options)
        {
            if (options.SelectExpand == null)
                return;

            options.Request.ODataFeature().SelectExpandClause = options.SelectExpand.SelectExpandClause;
        }
    }
}
