using System.Linq;
using Microsoft.AspNet.OData.Extensions;
using Microsoft.AspNet.OData.Query;

namespace AutoMapper.AspNet.OData
{
    public static class ODataQueryOptionsExtensions
    {

        /// <summary>Adds the count options to the result.</summary>
        /// <typeparam name="TModel">The type of the model.</typeparam>
        /// <typeparam name="TData">The type of the entity.</typeparam>
        /// <param name="options">The odata options.</param>
        /// <param name="query"></param>
        /// <autogeneratedoc />
        public static void AddCountOptionsResult<TModel, TData>(this ODataQueryOptions<TModel> options, IQueryable<TData> query)
        {
            if (options.Count == null || !options.Count.Value)
                return;

            options.Request.ODataFeature().TotalCount = query.LongCount();
        }
    }
}
