name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Variables
      run: |
        echo '::set-env name=DEPLOY_PACKAGE_URL::https://api.nuget.org/v3/index.json'
        echo '::set-env name=DEPLOY_PACKAGE_API_KEY::${{ secrets.NUGET_API_KEY }}'
        echo '::set-env name=REPO::${{ github.repository }}'
        echo '::set-env name=REPO_OWNER::${{ github.repository_owner }}'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - run: echo '::set-env name=PROJECT_NAME::AutoMapper.AspNetCore.OData.EFCore'
    - name: Pack and push
      run: ./Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::AutoMapper.AspNet.OData.EF6'
    - name: Pack and push
      run: ./Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::AutoMapper.AspNetCore.OData.EF6'
    - name: Pack and push
      run: ./Pack_Push.ps1
      shell: pwsh
